server:
  port: 9020

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9010/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: eureka-ribbon-feign
